/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get credential status
         * @description Report sanitized GCP Application Default Credential availability.
         */
        get: operations["auth-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List connection profiles
         * @description List local GCP connection profiles without credentials.
         */
        get: operations["list-profiles"];
        put?: never;
        /**
         * Create connection profile
         * @description Create a local profile containing a display name and GCP project ID.
         */
        post: operations["create-profile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update connection profile
         * @description Replace the name and GCP project ID of a local connection profile.
         */
        put: operations["update-profile"];
        post?: never;
        /**
         * Delete connection profile
         * @description Delete a local connection profile; cloud resources are not changed.
         */
        delete: operations["delete-profile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Cloud Run logs
         * @description Query a bounded time window of Cloud Run revision logs and return normalized entries plus an opaque cursor.
         */
        post: operations["query-logs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/request-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get request context
         * @description Find up to 200 Cloud Run revision entries across all services in the profile project, within 15 minutes before or after the selected event, by exact known request ID or trace ID locations.
         */
        post: operations["request-context"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Invalidate the current local session and expire its cookie.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pair browser session
         * @description Exchange the single-use startup token for a local HttpOnly session cookie.
         */
        post: operations["pair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover Cloud Run services
         * @description List Cloud Run services for a profile; an all-logs fallback and sanitized warning header are returned when discovery fails.
         */
        get: operations["discover-sources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthStatusOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/AuthStatusOutputBody.json
             */
            readonly $schema?: string;
            /** @description Whether Application Default Credentials are available. */
            available: boolean;
            /** @description Sanitized credential status message. */
            message: string;
        };
        CookieOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/CookieOutputBody.json
             */
            readonly $schema?: string;
            /** @description Whether pairing succeeded. */
            paired: boolean;
        };
        Entry: {
            /** @description Common HTTP request metadata. */
            httpRequest?: components["schemas"]["HTTPRequest"];
            /** @description Stable provider-derived identity for this exact log entry. */
            id: string;
            /** @description GCP log entry labels. */
            labels: {
                [key: string]: string;
            };
            /** @description Display message selected from the structured or text payload. */
            message: string;
            /** @description Exact payload path selected for message. */
            messageSource: string;
            /** @description Original GCP LogEntry JSON. */
            raw: unknown;
            /**
             * Format: date-time
             * @description Cloud Logging receive timestamp.
             */
            receiveTimestamp?: string;
            /** @description Request ID found in a common structured payload location. */
            requestId?: string;
            /** @description Normalized GCP severity name. */
            severity: string;
            /** @description Original top-level GCP severity, or original JSON level when it supplies the normalized severity. */
            severityOriginal: string;
            /** @description Normalized service or monitored resource name. */
            source: string;
            /** @description Original GCP log name. */
            sourceOriginal: string;
            /** @description Cloud Trace span ID. */
            spanId?: string;
            /** @description Decoded jsonPayload, or null for non-JSON entries. */
            structured: {
                [key: string]: unknown;
            } | null;
            /**
             * Format: date-time
             * @description Event timestamp.
             */
            timestamp: string;
            /** @description Trace resource name or trace identifier. */
            trace?: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        FieldPredicate: {
            /**
             * @description Exact structured-field comparison operator.
             * @enum {string}
             */
            operator: "equals" | "contains" | "exists" | "gt" | "lt";
            /** @description Dot-separated structured payload path, optionally prefixed with jsonPayload. Each segment must start with a letter or underscore and contain only letters, digits, and underscores. */
            path: string;
            /** @description Comparison value: string, number, or boolean for equals; string for contains; boolean for exists; number for gt or lt. */
            value: unknown;
        };
        HTTPRequest: {
            /** @description Request latency as a protobuf duration. */
            latency?: string;
            /** @description HTTP request method. */
            method?: string;
            /** @description HTTP protocol used for the request. */
            protocol?: string;
            /** @description HTTP referrer. */
            referer?: string;
            /** @description Originating client IP as reported by Cloud Logging. */
            remoteIp?: string;
            /**
             * Format: int64
             * @description HTTP response status code.
             */
            status?: number;
            /** @description Requested URL. */
            url?: string;
            /** @description HTTP user agent. */
            userAgent?: string;
        };
        MessageOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/MessageOutputBody.json
             */
            readonly $schema?: string;
            message: string;
        };
        PairInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/PairInputBody.json
             */
            readonly $schema?: string;
            /** @description Single-use pairing token from the startup URL fragment. */
            token: string;
        };
        ProfileBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/ProfileBody.json
             */
            readonly $schema?: string;
            /** @description User-visible connection name. */
            name: string;
            /** @description GCP project ID; credentials are never stored. */
            projectId: string;
        };
        ProfileResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/ProfileResponse.json
             */
            readonly $schema?: string;
            /** @description Stable local connection profile ID. */
            id: string;
            /** @description User-visible connection name. */
            name: string;
            /** @description GCP project ID. */
            projectId: string;
            /**
             * @description Cloud provider.
             * @enum {string}
             */
            provider: "gcp";
            /**
             * @description Current local credential status.
             * @enum {string}
             */
            status: "ready" | "needs-auth";
        };
        QueryInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/QueryInputBody.json
             */
            readonly $schema?: string;
            /** @description Opaque cursor returned by the preceding identical query. */
            cursor?: string;
            /**
             * Format: date-time
             * @description Exclusive absolute end timestamp, no more than seven days after start.
             */
            end: string;
            /**
             * Format: int64
             * @description Maximum entries to return.
             */
            limit: number;
            /**
             * @description Query language mode; native passes query as a GCP Logging filter fragment.
             * @enum {string}
             */
            mode: "leopard" | "structured" | "native";
            /** @description Provider-neutral structured payload predicates. Only valid in structured mode; all predicates are combined with AND. */
            predicates?: components["schemas"]["FieldPredicate"][] | null;
            /** @description Connection profile ID. */
            profileId: string;
            /** @description Search expression or native GCP filter fragment, according to mode. */
            query?: string;
            /** @description Exact normalized severities to include; WARN is accepted as WARNING. */
            severities?: string[] | null;
            /** @description Cloud Run service names to include. */
            sources?: string[] | null;
            /**
             * Format: date-time
             * @description Inclusive absolute start timestamp.
             */
            start: string;
        };
        QueryOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/QueryOutputBody.json
             */
            readonly $schema?: string;
            /** @description Normalized log entries in descending timestamp order. */
            entries: components["schemas"]["Entry"][] | null;
            /**
             * Format: date-time
             * @description Cursor expiry timestamp.
             */
            expiresAt: string;
            /** @description Opaque cursor for the next page. */
            nextCursor?: string;
        };
        RequestContextInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/RequestContextInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: date-time
             * @description Selected event timestamp at the center of the context window.
             */
            eventTimestamp: string;
            /** @description Connection profile ID. */
            profileId: string;
            /** @description Exact request ID from the selected event. At least requestId or traceId is required. */
            requestId?: string;
            /** @description Exact trace resource name or trace ID from the selected event. At least requestId or traceId is required. */
            traceId?: string;
        };
        RequestContextOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/RequestContextOutputBody.json
             */
            readonly $schema?: string;
            /** @description Matching Cloud Run revision entries across all services, in ascending timestamp order. */
            entries: components["schemas"]["Entry"][] | null;
        };
        SourceResponse: {
            /** @description Cloud Run service name; empty means all Cloud Run revision logs. */
            id: string;
            /**
             * @description Source selector kind.
             * @enum {string}
             */
            kind: "cloud-run" | "log";
            /** @description User-visible source label. */
            label: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-profile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-profile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "query-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "request-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestContextInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestContextOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CookieOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    pair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CookieOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "discover-sources": {
        parameters: {
            query: {
                /** @description Connection profile ID. */
                profileId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-LogLeopard-Warning"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
